name: Bug Report
description: File a reproducible bug or defect in Zyphor
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report an issue!
  - type: input
    id: os
    attributes:
      label: Operating System & Build
      placeholder: Windows 11 23H2 (Build 22631.3007)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this problem?
    validations:
      required: true
