name: Feature Request
description: Propose a new feature, screen, or platform backend
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Propose new ideas or hardware capabilities for Zyphor.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed hardware or UI solution.
    validations:
      required: true
